
ERR_ALIGNMENT_CMN_BIT =		0x00110000

ERR_ALIGNMENT_NOERR =						(0)
ERR_ALIGNMENT_4PT_VERIFY_PARAM_X =		(ERR_ALIGNMENT_CMN_BIT | 0x001F)	# 内部エラー：
ERR_ALIGNMENT_4PT_VERIFY_PARAM_Y =		(ERR_ALIGNMENT_CMN_BIT | 0x0020)
ERR_ALIGNMENT_4PT_VERIFY_DIST_X =			(ERR_ALIGNMENT_CMN_BIT | 0x0021)
ERR_ALIGNMENT_4PT_VERIFY_DIST_Y =			(ERR_ALIGNMENT_CMN_BIT | 0x0022)
ERR_ALIGNMENT_LSM_THETA =					(ERR_ALIGNMENT_CMN_BIT | 0x0023)
ERR_ALIGNMENT_CAL_NEW_4POINTS =			(ERR_ALIGNMENT_CMN_BIT | 0x0024)
ERR_ALIGNMENT_MARK_NUM =					(ERR_ALIGNMENT_CMN_BIT | 0x0025)
ERR_ALIGNMENT_SCALING_PARAM =				(ERR_ALIGNMENT_CMN_BIT | 0x0026)
ERR_ALIGNMENT_KX_VALUE =					(ERR_ALIGNMENT_CMN_BIT | 0x0027)
ERR_ALIGNMENT_KY_VALUE =					(ERR_ALIGNMENT_CMN_BIT | 0x0028)
ERR_ALIGNMENT_VERIFY_THETA =				(ERR_ALIGNMENT_CMN_BIT | 0x0029)
ERR_ALIGNMENT_VERIFY_DIST =				(ERR_ALIGNMENT_CMN_BIT | 0x002A)
ERR_ALIGNMENT_VERIFY_ANS =				(ERR_ALIGNMENT_CMN_BIT | 0x002B)
ERR_ALIGNMENT_POINT_VAL_ERR =				(ERR_ALIGNMENT_CMN_BIT | 0x002C)
ERR_ALIGNMENT_DIST_ADJUST_ERROR =			(ERR_ALIGNMENT_CMN_BIT | 0x002D)
ERR_ALIGNMENT_DIST_ANUULARING_ERROR =		(ERR_ALIGNMENT_CMN_BIT | 0x002E)
ERR_ALIGNMENT_INVALID_AREA_NUM =			(ERR_ALIGNMENT_CMN_BIT | 0x002F)
ERR_ALIGNMENT_INVALID_ALIGN_MODE =		(ERR_ALIGNMENT_CMN_BIT | 0x0030)
ERR_ALIGNMENT_DIST_CONTROL_ON_FIX =		(ERR_ALIGNMENT_CMN_BIT | 0x0031)
ERR_ALIGNMENT_VFY_CORR_ERR_VAL_X =		(ERR_ALIGNMENT_CMN_BIT | 0x0032)
ERR_ALIGNMENT_VFY_CORR_ERR_VAL_Y =		(ERR_ALIGNMENT_CMN_BIT | 0x0033)
ERR_ALIGNMENT_INVALID_BOARD_SCALE_MODE =	(ERR_ALIGNMENT_CMN_BIT | 0x0034)
ERR_ALIGNMENT_INVALID_AREA_SCALE_MODE =	(ERR_ALIGNMENT_CMN_BIT | 0x0035)

#[S] #1453 多点アライメント対応
ERR_ALIGNMENT_GJ_CALCU_ERR =				(ERR_ALIGNMENT_CMN_BIT | 0x0036)	# 射影変換時エラー
#[E] #1453 多点アライメント対応

ERR_ALIGNMENT_INVALID_MARK_SET =			(ERR_ALIGNMENT_CMN_BIT | 0x0050)	# 外部通知用：マーク配置エラー専用

#endif	# _ALIGNMENT_CMN_H_

ALIGNMENT_DEBUG_PRINT = False